### ISSUE TITLE
Command Cleanup and Testing

### ISSUE THREAD

**Issue by UberPilot** [jet-suite/JetEngine#12]
### SonarQube
Resolve SonarQube issues as outlined [here](https://sonarcloud.io/code?id=jet-suite_JetEngine&selected=jet-suite_JetEngine%3Asrc%2Fmain%2Fjava%2Fme%2Fuberpilot%2Fjetengine%2Fcommand%2FCommand.java).

### Tasks
- [x] Resolve SonarQube issues
- [x] Bring test coverage up to 100%
- [x] Fix late-adding children to commands
