### ISSUE TITLE
JetEngine and JPlugin Cleanup

### ISSUE THREAD

**Issue by UberPilot** [jet-suite/JetEngine#13]
### SonarQube
Resolve SonarQube issues as outlined [here (JetEngine)](https://sonarcloud.io/code?id=jet-suite_JetEngine&selected=jet-suite_JetEngine%3Asrc%2Fmain%2Fjava%2Fme%2Fuberpilot%2Fjetengine%2FJetEngine.java) and [here (JPlugin)](https://sonarcloud.io/code?id=jet-suite_JetEngine&selected=jet-suite_JetEngine%3Asrc%2Fmain%2Fjava%2Fme%2Fuberpilot%2Fjetengine%2FJPlugin.java).

### Tasks
- [x] Resolve SonarQube issues
  - [x] Reduce complexity of large methods
  - [x] Write utility methods
  - [x] Follow standards
